### ISSUE TITLE
Bohr radius correct?

### ISSUE THREAD

**Issue by MarkusLippitz** [tpolakovic/SimpleQuantum#15]
Hi Tomas

I really like your blog post and this package! I am however puzzled by the energy scale of the Al band structure. (But I am not used to Hartree units). The Fermi energy of Al should be around 11 eV, but looking at your plots its rather 5 Ha = 135 eV. I think this is because a0 = 1.8Å is not really the Bohr radius of approx 0.5Å.

When changing a0 to the traditional Bohr radius, the energy scales fit for the case V=0, but the potential seems to need some other parameter.

Best regards
Markus

**Comment by tpolakovic** [comment]
You're right, I mistakenly flipped the unit conversion. The Al calculation is just a toy model and the parameter is free to be fit so that the band structure at least qualitatively looks correct. I'll fix that soon.

As for the absolute value of the Fermi energy, it's not reasonable for it have a specific value when the zero frequency component of a potential is not physically correct (in this case it's artificially set to 0). In that sense, it looks more or less right in that it's close to the top of the n=1 band at the W point (see, e.g., [here](https://materialsproject.org/materials/mp-134?chemsys=Al)). Because I set the potential parameter to recover correct-looking bands even with the wrong unit scale, that shouldn't change after I fix the bug.
